### ISSUE TITLE
Support for G5 without nightscout

### ISSUE THREAD

**Issue by SamuelAlinder** [mddub/urchin-cgm#11]
Hello.. It would be good to have a way to use G5 data using Bridge username/PW
(since nightscout for G5 outside US is not available yet.)

**Comment by mddub** [comment]
This was added in #59, which is part of the latest release (v0.0.14).

**Comment by SamuelAlinder** [comment]
hmm.. did not get it to work.. where is the code for this?

**Comment by mddub** [comment]
What are the symptoms of the issue you are experiencing? What do you see in the settings page and on the watch?

Latest release is here:
https://raw.githubusercontent.com/mddub/urchin-cgm/master/release/urchin-cgm.pbw

Most of the code is here:
https://github.com/mddub/urchin-cgm/blob/master/src/js/data.js#L966-L1046

**Comment by SamuelAlinder** [comment]
sorry.. responded to the wrong issue..
