### ISSUE TITLE
Data points hidden by grey range lines

### ISSUE THREAD

**Issue by scottleibrand** [mddub/urchin-cgm#12]
When a BG is at the high or low end of the target range, it is covered up by the grey line that denotes the edge of the target range. It should instead appear on top of the grey line

**Comment by mddub** [comment]
D'oh. Thanks for reporting! I changed the way those lines are drawn [recently](https://github.com/mddub/urchin-cgm/commit/2736df#diff-ee64725c0d114c173d27e02b0825f000L78), but tested on Aplite only. Fixed this in https://github.com/mddub/urchin-cgm/commit/5fe7de, which is in the [newest release](https://github.com/mddub/urchin-cgm/compare/27f367...150be0).
