### ISSUE TITLE
Current pbw doesn't display iob in status bar if running openaps ama

### ISSUE THREAD

**Issue by audiefile** [mddub/urchin-cgm#16]
I recently switched to openaps ama and can no longer see iob in status bar. I noticed data.js has code for this but it doesn't seem to be in the current 'released' watch face.

**Comment by mddub** [comment]
Oops, thanks for bringing this up. Just bumped `release/urchin-cgm.pbw` to include the latest.

**Comment by audiefile** [comment]
Fabulous! Thank you
