### ISSUE TITLE
mmol settings

### ISSUE THREAD

**Issue by Zaning** [mddub/urchin-cgm#18]
Despite changing the watch fact to mmol I am still unable to drop the vales below 30. Every time i change the value and save it simply reverts to the minimum of 30. 

Thanks

**Comment by mddub** [comment]
Do you mean the graph settings? The numbers for the top/bottom of the graph/target range are always expressed in mg/dL, even if you're showing BG in mmol/L.

**Comment by Zaning** [comment]
Ah ok thanks that makes sense. So I just need to convert my values and it will work in mmol/L. Awesome project. I watched your presentation on youtube the other day and it was a real inspiration.

**Comment by mddub** [comment]
Thanks, really appreciate that. <3
