### ISSUE TITLE
COB?  Need to see along with IOB.

### ISSUE THREAD

**Issue by KeesaKat** [mddub/urchin-cgm#26]
Totally like the flexibility of your watch face and all it can show. Is my preferred face for length of graph,  raw data, basal info and bolus info BUT as an adult T1 need to see BOTH my IOB as well as my COB to be able to keep the tight control I want with out stacking bolus insulin.  Is there a way to set it up to pull both IOB as well as COB from NS? I enter that data via care portal and can see on website but want it on my wrist as I can't make good decisions on when to nudge the line up or down with temp basal changes or micro bolus aka Sugar Surfing  when I can't see IOB, COB and time frame of last bolus.

**Comment by mddub** [comment]
Does your Nightscout server show the number you expect after `"cob"` if you go to `https://your.nightscout.site/pebble`? (You may need to turn on the [cob plugin](https://github.com/nightscout/cgm-remote-monitor#built-inexample-plugins).) If so, this shouldn't be too hard.

In the Urchin status bar, would you want to see something like `2.8u 34g`?

**Comment by KeesaKat** [comment]
I have COB plugin enabled in NS and can get both IOB and COB to show in the CGM Skyline watch face. Would like to pull the same data into Urchin as it has the longer time line for graph and can show when bolus dose was given.
So if possible to show IOB and COB on the same line  like  2.8 U   38 g would be perfect.
Thanks for looking at it.

**Comment by mddub** [comment]
Thanks for the suggestion. I just released this in [v0.0.11](https://github.com/mddub/urchin-cgm/releases/tag/v0.0.11), so re-install the app and try the "Insulin + carbs on board" option.

**Comment by KeesaKat** [comment]
Thanks for doing this!  Just downloaded and playing with the options now   - - - like the color options as well!

Marybeth

On August 23, 2016, at 7:16 PM, Mark Wilson notifications@github.com wrote:

Thanks for the suggestion. I just released this in v0.0.11, so re-install the app and try the "Insulin + carbs on board" option.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mddub/urchin-cgm","title":"mddub/urchin-cgm","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/mddub/urchin-cgm">https://github.com/mddub/urchin-cgm</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mddub in #26: Thanks for the suggestion. I just released this in [v0.0.11][1], so re-install the app and try the \"Insulin + carbs on board\" option.\r\n\r\n[1]: <a href="https://github.com/mddub/urchin-cgm/releases/tag/v0.0.11">https://github.com/mddub/urchin-cgm/releases/tag/v0.0.11</a>"}],"action":{"name":"View Issue","url":"<a href="https://github.com/mddub/urchin-cgm/issues/26#issuecomment-241910001">https://github.com/mddub/urchin-cgm/issues/26#issuecomment-241910001</a>"}}}

**Comment by KeesaKat** [comment]
Mark, 
Would mention that temp basal rates don't seem to import properly. I can enter to NS  via care portal app and will show in NS correctly but does not pull to Urchin if the time frame for a temp basal is longer then 30 minutes. 
Will show as NaNu/h NaNu with a number in ( ) that increments up over time. NS shows the basal as a T:0.75 or what ever the amount the actual rate becomes in the basal pill, and shows the +/- % increment in the basal rendition.
If it's 30minutes duration, Urchin seems to like it better.

-----Original Message-----

**Comment by mddub** [comment]
Thanks for reporting. Did you enter the temp basal with the Care Portal app for Pebble, or on the Nightscout web interface? Do the temp basals show up correctly on the Urchin graph if you check "Show basal rate history"?

Can you go to `https://your.nightscout.site/api/v1/treatments.json?find[eventType]=Temp+Basal&count=20` and paste your data into a Gist at https://gist.github.com/? You can share the link here, or make the Gist private and email it to me if you prefer.

**Comment by KeesaKat** [comment]
From care portal app tonight , but believe  I have seen it happen when entered directly via website too.

Marybeth

On August 23, 2016, at 8:50 PM, Mark Wilson notifications@github.com wrote:

Reopened #26.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mddub/urchin-cgm","title":"mddub/urchin-cgm","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/mddub/urchin-cgm">https://github.com/mddub/urchin-cgm</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Reopened #26."}],"action":{"name":"View Issue","url":"<a href="https://github.com/mddub/urchin-cgm/issues/26#event-765330670">https://github.com/mddub/urchin-cgm/issues/26#event-765330670</a>"}}}

**Comment by mddub** [comment]
Thanks. Please send me that data next time it happens so I can figure out what's going wrong.

**Comment by mddub** [comment]
Closing this; please reopen if you see this issue again and can send data.
