### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by francesc0-cgm** [mddub/urchin-cgm#43]
When alerts will be implemented? Thank you

(EDIT: we can use nightwatch notification on android and pushover notification on ios to get them so it is not a true urgency)

**Comment by francesc0-cgm** [comment]
Timeago indication too will be possibile?

**Comment by francesc0-cgm** [comment]
Sorry Mark...another question...24 hrs time mode is yet available?

**Comment by mddub** [comment]
The clock will display as 12 or 24 hour time depending on your Pebble settings (Settings > Date & Time > Time Format).

Alarms and timeago are both on the roadmap (see "To do" in the README). Nightscout already has highly configurable cross-platform alarms via Pushover, so this is really only necessary for direct-from-Share and "camping" mode, neither of which I've officially released.

This being a free, volunteer, open-source project, I can't commit to a time when specific new features will be added. If you want to contribute a PR, I'm happy to lend support. If a particular feature is very important to you and you're interested in sponsoring its development, I'm happy to discuss over email.

**Comment by francesc0-cgm** [comment]
Thank you Mark.

Inviato con AquaMail per Android
http://www.aqua-mail.com

Il 14 settembre 2016 10:12:22 PM Mark Wilson notifications@github.com ha 
scritto:
