### ISSUE TITLE
Line between points not using "Same as next point" color choice

### ISSUE THREAD

**Issue by Pogman** [mddub/urchin-cgm#51]
When using the "Line color" option and setting "Same as next point" the line is always colored black and does not use the next points color.

I have a number of missed readings during the day and use the "Draw line between points" to have a continuous graph but it always has patches of black rather then colored as selected.

**Comment by mddub** [comment]
Thanks for reporting. Can you share a picture, and some values from `/api/v1/entries.json` from around the same time?

I would expect it to look like this:

![testpointscolorlinewithmissingpoints-basalt](https://cloud.githubusercontent.com/assets/1026240/19330114/42dd7f38-9091-11e6-8717-6aa17beb8562.png)
https://github.com/mddub/urchin-cgm/blob/5cbe440/test/test_screenshots.py#L589-L590

**Comment by Pogman** [comment]
Yeah forget about the gaps and missed readings that's just how I noticed it due to having it show 4 hours of data. When I set my graph similar to that image all the lines appear black and not the next color.

Now what I noticed is that I initially went and selected a custom color and saved then when back and set it to use next color but will always use the custom color and not obey the next color option.

**Comment by mddub** [comment]
Can you send a screenshot of your graph settings and what you see on the watch? Thanks!

**Comment by Pogman** [comment]
![pebcgm4](https://cloud.githubusercontent.com/assets/7413594/19348570/7ead84f8-9146-11e6-85a9-1eff1e62beaf.jpg)
![pebcgm3](https://cloud.githubusercontent.com/assets/7413594/19348569/7eab10e2-9146-11e6-9fa3-849177d12b27.jpg)
![pebcgm2](https://cloud.githubusercontent.com/assets/7413594/19348571/7eadeaf6-9146-11e6-8b7e-23b7c2430884.jpg)
![pebcgm1](https://cloud.githubusercontent.com/assets/7413594/19348572/7eb21f36-9146-11e6-82b2-792d1598b325.jpg)

**Comment by mddub** [comment]
Thanks! I see what the problem is - it's actually a bug in the Pebble Android app which I had to work around once before, then promptly forgot about. Just added the more universal fix in #53 to the latest release. Please give it a try and confirm that fixes it for you.

**Comment by Pogman** [comment]
Looks good - not a comprehensive test but for my 4 hour graph I see all the correct colors where there would be definite breaks before and there have been missed readings in the last hour too. Nice.

**Comment by mddub** [comment]
Great! Thanks for the help.
