### ISSUE TITLE
Watchface unsupported 

### ISSUE THREAD

**Issue by Renjirai** [mddub/urchin-cgm#75]
On my androin 5.1 samsung doesn't work URCHIN watchface. Application pebble of the last version shows that it's unsupported watchface. Developermode is on. Watches is pebble time round. May be could anyone know what's the problem. Or could You just tell what pebble watches support Your URCHIN watchface?
![photo_2018-06-23_16-12-53](https://user-images.githubusercontent.com/40513924/41809532-56f52ef6-7700-11e8-86fb-a83a096e429f.jpg)

**Comment by Pogman** [comment]
AFAIK Urchin does not work with the round - all the other Pebbles do.
