### ISSUE TITLE
Battery Status Indicator Type and Location

### ISSUE THREAD

**Issue by channemann** [mddub/urchin-cgm#9]
Feature Requests:
- Permit toggle between battery status icon and percentage
- Make location of battery status fully configurable (i.e. which area it appears in and where it appears within that area)

**Comment by mddub** [comment]
Added battery as percentage in https://github.com/mddub/urchin-cgm/commit/ad320e. Fully configurable battery location is a little more complex and frankly pretty low priority, but I do think that as long as "status bar" means "kind of on the right edge of the status bar," it makes sense to vertically align it to the lowest line of text, so I added that in https://github.com/mddub/urchin-cgm/commit/477cca.

Is there somewhere else in particular you'd want to put the battery?

**Comment by channemann** [comment]
For me, that's perfect.

**Comment by mddub** [comment]
:thumbsup:
